[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src *; media-src *; style-src * 'nonce-inlined-styles'"
    Permissions-Policy = "interest-cohort=()"
